/// Flutter icons Challeng_05
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Challeng_05
///      fonts:
///       - asset: fonts/Challeng_05.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class Challeng_05 {
  Challeng_05._();

  static const _kFontFam = 'Challeng_05';

  static const IconData business_center = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData food = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData doc = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData map_marker = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData town_hall = const IconData(0xe83c, fontFamily: _kFontFam);
}
